"""Lookup utilities for dbSNP Parquet outputs.

This module provides lightweight query helpers over per-chromosome dbSNP
lookup Parquet files generated by the pipeline.

In ideal cases, you already know which chromsome holds a specific rsID. In this case,
its most efficient to just query the respective chromosome file.

Example:
    from pyvariantdb.lookup import SNPLookup

    lookup = SNPLookup()
    # P53 mutations, chromosome 17
    rsids = ["rs1042522", "rs17878362", "rs1800372"]
    df_all = lookup.query_all(rsids)
    df_chr = lookup.query_chromosome(rsids, "17")
    print(df_all)
    print(df_chr)
"""

from __future__ import annotations

import polars as pl
from loguru import logger
from pathlib import Path
from typing import Optional

from pyvariantdb.const import get_cache_dir

DEFAULT_VERSION = "156"
DEFAULT_OUTPUT_DIR = "output"


class SNPLookup:
    """Query dbSNP lookup Parquet files by rsID.

    Example:
        lookup = SNPLookup(version="156")
        rsids = ["rs1042522", "rs17878362", "rs1800372"]
        df = lookup.query_all(rsids)
        print(df)
    """

    def __init__(self, version: str = DEFAULT_VERSION, cache_dir: Optional[str] = None):
        self.version = version
        self.cache_dir = Path(cache_dir) if cache_dir else get_cache_dir() / DEFAULT_OUTPUT_DIR

    def query_all(self, rsids: list[str]) -> pl.DataFrame:
        """Query all lookup files for a list of rsIDs.

        Args:
            rsids: List of rsIDs to search for.

        Returns:
            A Polars DataFrame with columns "RSID" and "ID".

        Example:
            lookup = SNPLookup()
            rsids = ["rs1042522", "rs17878362", "rs1800372"]
            df = lookup.query_all(rsids)
            print(df.head(3))
        """
        logger.info(f"Querying dbSNP Parquet files for {len(rsids)} rsIDs...")
        if not rsids:
            return pl.DataFrame(schema={"RSID": pl.String, "ID": pl.String})

        pattern = f"dbSNP_{self.version}.chr*.lookup.parquet"
        lookup_files = sorted(self.cache_dir.glob(pattern))
        if not lookup_files:
            raise FileNotFoundError(f"No dbSNP Parquet files found in {self.cache_dir}")

        lazy_frames = []
        for in_file in lookup_files:
            lazy_frames.append(
                pl.scan_parquet(in_file).filter(pl.col("RSID").is_in(rsids))
            )

        return pl.concat(lazy_frames).collect()

    def query_chromosome(self, rsids: list[str], chrom: str) -> pl.DataFrame:
        """Query a specific chromosome lookup file for a list of rsIDs.

        Args:
            rsids: List of rsIDs to search for.
            chrom: Chromosome label, e.g. "chr17" or "17".

        Returns:
            A Polars DataFrame with columns "RSID" and "ID".

        Example:
            lookup = SNPLookup()
            rsids = ["rs1042522", "rs17878362", "rs1800372"]
            df = lookup.query_chromosome(rsids, "17")
            print(df)
        """
        logger.info(f"Querying dbSNP Parquet files for {len(rsids)} rsIDs...")
        if not rsids:
            return pl.DataFrame(schema={"RSID": pl.String, "ID": pl.String})

        chrom_label = chrom if chrom.startswith("chr") else f"chr{chrom}"
        in_file = self.cache_dir / f"dbSNP_{self.version}.{chrom_label}.lookup.parquet"
        if not in_file.exists():
            raise FileNotFoundError(f"dbSNP Parquet file not found: {in_file}")

        subset_df = (
            pl.scan_parquet(in_file)
            .filter(pl.col("RSID").is_in(rsids))
            .collect()
        )
        return subset_df
